[RFC] Add interface for dimensions.
ArpNetworking/metrics-client-nodejs pull request #6
Opened 2016-09-06 23:54 UTC by matthayter

Hi team,

We've decided to go with just adding `String, String` dimensions for now in order to not diverge from the path of the OSS project. This PR requests validation of the addition to the interface needed for such an implementation of dimensions. Implementation is currently being worked on.

2016-09-09 08:00 UTC, vjkoskela commented on src/defs/metrics.d.ts
> +        addDimension(key:string, value:string): void;
You should also have an ```addAnnotations``` which accepts a map.

2016-09-09 08:00 UTC, vjkoskela commented
Not sure why you want to start with the node client since it was never brought up to previous spec levels.

2016-09-16 19:34 UTC, matthayter commented on src/defs/metrics.d.ts
> +        addDimension(key:string, value:string): void;
Done - added `addAnnotations` and `addDimensions`

2016-09-16 19:35 UTC, matthayter commented
Currently bringing it up to 2G for use by our internal clients.

2016-09-16 19:39 UTC, matthayter commented
Tests failed due to lowered coverage, ignoring for this RFC

2016-09-16 20:06 UTC, BrandonArp commented
This looks good to me.

2016-09-17 16:08 UTC, vjkoskela commented on src/defs/metrics.d.ts
>          annotate(key:string, value:string): void;
This should either be renamed or marked deprecated and the consistently named version added.

2016-09-17 16:20 UTC, vjkoskela requested changes
Please do compare this against the 2f spec which you have.

2016-09-22 20:28 UTC, matthayter commented on src/defs/metrics.d.ts
>          annotate(key:string, value:string): void;
Have done so in the 2f PR #7

2016-09-22 20:28 UTC, matthayter commented
Closing this; I'll be implementing this interface in the upcoming 2G PR.

2016-09-22 20:28 UTC, closed without merging