2G - part 1 of 2
ArpNetworking/metrics-client-nodejs pull request #8
Opened 2016-10-05 23:17 UTC by matthayter

Reopening with all comments addressed from #7

2016-10-09 00:15 UTC, vjkoskela requested changes
Okay, just some minor feedback and responses to the closed PR (#7). I think after this we can merge this, but there's still a lot left to do before this can be released. This is neither 2F nor 2G.

2016-10-09 00:15 UTC, vjkoskela commented on README.md
> +This will write the metrics to file named ```query.log``` with rotation size of 32MB and retention of the last 10 logs
Does this still match the defaults?

2016-10-09 00:15 UTC, vjkoskela commented on src/sinks/tsd-query-log-sink.ts
>          var transformedMetricsEvent = TsdQueryLogSink.transformMetricsEvent(metricsEvent);
So in 2F we supported both a standard json format and a steno json format. I know you are skipping 2f, but this looks like the non-steno sink in Java and it implements steno.

2016-10-09 00:15 UTC, vjkoskela commented on src/tsd-metrics-factory.ts
> +                hostResolver = new hostResolvers.DefaultHostResolver(options.hostName)
Doesn't the default host resolver get the hostname from the operating system?

-> Consider a different "static" host provider for representing a user specified host name.

2016-10-09 00:15 UTC, vjkoskela commented on src/tsd-default-options.ts
> +    public static LOG_MAX_SIZE:number = 100 * 1024 * 1024;
Please add a TODO somewhere appropriate referencing a (new) issue that the NodeJS client needs to implement time-based file rotation.

2016-10-09 00:15 UTC, vjkoskela commented on src/tsd-metrics-factory.ts
> +    private static defaultHostResolver = new hostResolvers.DefaultHostResolver(os.hostname());
You should have two host name providers:

1) Accepts a static hostname and serves that back.
2) Returns the hostname from the os. 

Calling the OS from here defeats the point of the encapsulation.

If you want to implement more depth here, we have two additional host providers in Java:

1) Caching; caches the os hostname for a period of time but refreshes inline (e.g. when user calls getHostname).
2) Background refresh; caches the hostname and uses a thread (in JS a timer and handler) to refresh the cached name periodically without blocking user requests.

2016-10-09 00:15 UTC, vjkoskela commented on src/tsd-metrics-factory.ts
> +    public static buildInstance(options: {serviceName:string; clusterName:string; hostName?:string; hostResolver?:tsdDef.HostResolver; sinks?:tsdDef.Sink[]; logger?:log4js.Logger}):TsdMetricsFactory
Why would you accept the host name and host resolver in the method? Is the idea that only one is provided (e.g. arguments by name)?

2016-10-11 22:30 UTC, matthayter commented on README.md
> +This will write the metrics to file named ```query.log``` with rotation size of 32MB and retention of the last 10 logs
Fixing...

2016-10-11 22:37 UTC, matthayter commented on src/sinks/tsd-query-log-sink.ts
>          var transformedMetricsEvent = TsdQueryLogSink.transformMetricsEvent(metricsEvent);
Ah you're saying this should really be named `TsdQueryLogStenoSink` or similar?

As an aside, I'm planning to drop steno with the second part of these changes with 2G.

2016-10-11 22:41 UTC, matthayter commented on src/tsd-metrics-factory.ts
> +    public static buildInstance(options: {serviceName:string; clusterName:string; hostName?:string; hostResolver?:tsdDef.HostResolver; sinks?:tsdDef.Sink[]; logger?:log4js.Logger}):TsdMetricsFactory
Correct: this method takes one argument called `options` which is an object with the specified interface. The interface specifies that both `hostName` and `hostResolver` are optional. If both are provided, `hostResolver` takes priority.

2016-10-11 22:45 UTC, matthayter commented on src/tsd-metrics-factory.ts
> +    private static defaultHostResolver = new hostResolvers.DefaultHostResolver(os.hostname());
Oof, okay, mis-communication. Hopefully its what you're looking for now.

2016-10-11 22:45 UTC, matthayter commented on src/tsd-metrics-factory.ts
> +                hostResolver = new hostResolvers.DefaultHostResolver(options.hostName)
Oof, okay, mis-communication. Hopefully its what you're looking for now.

2016-10-11 22:46 UTC, matthayter commented on src/tsd-default-options.ts
> +    public static LOG_MAX_SIZE:number = 100 * 1024 * 1024;
Done

2016-10-15 16:56 UTC, vjkoskela commented
Looks good Matt, can't wait to see part 2.

2016-10-15 16:56 UTC, merged